name: Wompi_Test

on:
  push:
    branches:
      - main

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Ejecutar pruebas
        run: |
          ./gradlew clean test
        working-directory: ./Wompi_Test

      - name: Publicar resultados de pruebas
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: ./Wompi_Test/build/reports/tests
